### ISSUE TITLE
Ghost of buttons in the top left of the viewport when dragging a SortableItem that contains them

### ISSUE THREAD

**Issue by turtureanu** [rodrigodagostino/svelte-sortable-list#13]
I have an application where I put the two inputs (date) into each Sortable item, here is the code I am using (with classes omitted, because I'm using Tailwind):

```svelte
<div>
  <SortableList
    direction="vertical"
    transitionDuration={200}
    hasLockedAxis={true}
    isLocked={$sortedScheduleType !== "manual-sort" ? true : false}
    on:sort={handleSort}
  >
    {#each $scheduleStore as item, index (item.book.id)}
      <SortableItem id={item.book.id.toString()} {index}>
        <div>
          <div>
            <Icon icon="mdi-book" />
            <span>
              {item.book.name}
            </span>
          </div>
          <div>
            <div>
              {#key item.from}
                {handleListSort()}
                <DateInput
                  text="start date"
                  id={`from-${item.book.id}`}
                  bind:value={$scheduleStore[index].from}
                />
              {/key}
            </div>
            <div>
              {#key item.until}
                {handleListSort()}
                <DateInput
                  text="end date"
                  id={`until-${item.book.id}`}
                  bind:value={$scheduleStore[index].until}
                />
              {/key}
            </div>
            <div>
              {#key scheduleSortType}
                {#if scheduleSortType === "manual-sort"}
                  <Handle>
                    <div>
                      <Icon icon="material-symbols:drag-indicator" />
                    </div>
                  </Handle>
                {/if}
              {/key}
            </div>
          </div>
        </div>
      </SortableItem>
    {/each}
  </SortableList>
</div>
```

DateInput being defined as such:

```svelte
<script lang="ts">
	let {
		text,
		id,
		isPicked = false,
		value = $bindable()
	}: { text: string; id: string; isPicked?: boolean; value: string | undefined } = $props();
</script>

<div>
	<input
		class="h-0 w-0 scale-0"
		type="date"
		name={`date-${id}`}
		id={`date-${id}`}
		bind:value
	/>
	<button
		class={`${isPicked ? 'variant-soft-secondary' : 'variant-soft-tertiary'} btn w-24 rounded-md`}
		><label for={`date-${id}`}>{text}</label></button
	>
</div>
```

As you can see I have a `input[type="date"]` that is hidden (as in not visible and without any size) and a `<button>` that contains a `<label>` with some text, this way when the `button` is pressed the `<label>` triggers the input.

Whenever I sort an item a **ghost image** of the buttons **flickers** in the **top left** corner of the viewport.

Here is a video on mobile (_although the same happens on desktop_) demonstrating the issue:

https://github.com/user-attachments/assets/eb56fee9-8830-4a81-af7f-9696a8657968

**Comment by rodrigodagostino** [comment]
The main thing that caught my attention was that after dropping the `<Ghost>` element, the only things flickering are those two buttons. And when reviewing your code, I noticed those are the only elements that are wrapped in a `{#key ...}` logic block. So my best guess is that they are probably re-rendered after dropping causing that particular flickering you’re experiencing.

I haven’t had a good reason to remove the `<Ghost>`’s content after dropping, but you’ve just given me one. And that’s the change I’ve deployed in version `0.10.13`. I haven’t been able to replicate the bug you reported, but hopefully this change will take care of that :)

Let me know!

**Comment by turtureanu** [comment]
Thank you! It now works as intended!

**Comment by NatumanyaGuy** [comment]
## Issue Still Persists

The ghost element issue mentioned in #13 is still occurring when using **shadcn-svelte** components, specifically:
- `<Button>`
- `<Select>`
- `<Combobox>`

While the original issue may have been resolved for standard HTML elements, shadcn-svelte components still display the ghost element during drag operations - even without passing `{#key}`.

## Steps to Reproduce
1. Use `SortableList` with shadcn-svelte components (Button, Select, or Combobox)
2. Initiate a drag operation
3. Observe that a ghost element appears alongside the dragged item - similar to this


Would it be possible to reopen this issue or investigate why shadcn-svelte components behave differently?
